import pg from "pg";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const migrationDir = join(here, "..", "jobsearch", "migrations");

function postgresMigration(filename) {
  let sql = readFileSync(join(migrationDir, filename), "utf8")
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/gi, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/TEXT NOT NULL UNIQUE COLLATE NOCASE/gi, "CITEXT NOT NULL UNIQUE")
    .replace(/TEXT UNIQUE COLLATE NOCASE/gi, "CITEXT UNIQUE")
    .replace(/\s+COLLATE NOCASE/gi, "")
    .replace(/\bREAL\b/gi, "DOUBLE PRECISION");
  if (filename === "003_complete_manager.sql") {
    const deferred = "ALTER TABLE applications ADD COLUMN resume_id BIGINT REFERENCES resumes(id) ON DELETE SET NULL;";
    sql = sql.replace(/ALTER TABLE applications ADD COLUMN resume_id[^;]+;/, "");
    const marker = "CREATE INDEX idx_resume_owner_active ON resumes(user_id,is_archived);";
    sql = sql.replace(marker, `${marker}\n${deferred}`);
  }
  return sql;
}

export function assertSafeDatabaseUrl(url, { allowProduction = false } = {}) {
  if (!/^postgres(?:ql)?:\/\//i.test(url || ""))
    throw new Error("A PostgreSQL URL is required");
  const database = new URL(url).pathname.slice(1).toLowerCase();
  if (!allowProduction && !database.endsWith("_test"))
    throw new Error("Refusing database operation: test database name must end in _test");
}

export async function migratePostgres(url, options = {}) {
  assertSafeDatabaseUrl(url, options);
  const local = /(?:localhost|127\.0\.0\.1)/i.test(url);
  const client = new pg.Client({
    connectionString: url,
    ssl: local ? false : { rejectUnauthorized: true },
    connectionTimeoutMillis: 10_000,
  });
  await client.connect();
  try {
    await client.query("CREATE EXTENSION IF NOT EXISTS citext");
    await client.query("CREATE TABLE IF NOT EXISTS schema_migrations(version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)");
    const applied = new Set((await client.query("SELECT version FROM schema_migrations")).rows.map(({ version }) => version));
    for (const filename of readdirSync(migrationDir).filter((name) => name.endsWith(".sql")).sort()) {
      if (applied.has(filename)) continue;
      await client.query("BEGIN");
      try {
        await client.query(postgresMigration(filename));
        await client.query("INSERT INTO schema_migrations(version) VALUES ($1)", [filename]);
        await client.query("COMMIT");
      } catch (error) {
        await client.query("ROLLBACK");
        throw error;
      }
    }
    const versions = await client.query("SELECT version FROM schema_migrations ORDER BY version");
    return versions.rows.map(({ version }) => version);
  } finally {
    await client.end();
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const url = process.env.DIRECT_URL || process.env.TEST_DATABASE_URL;
  const allowProduction = process.env.CONFIRM_PRODUCTION_MIGRATION === "yes-migrate-jobquest";
  migratePostgres(url, { allowProduction })
    .then((versions) => console.log(`Applied PostgreSQL migrations: ${versions.join(", ")}`))
    .catch((error) => {
      console.error(String(error.message).replace(/postgres(?:ql)?:\/\/\S+/gi, "[database-url]"));
      process.exitCode = 1;
    });
}
